'use strict';

const COLUMNS = [
  'title',
  'artist',
  'existing_year',
  'existing_year_source',
  'existing_status',
  'existing_notes',
  'csv_year',
  'estimated_year',
  'spotify_album_name',
  'spotify_album_type',
  'spotify_album_release_date',
  'spotify_duration_ms',
  'spotify_album_artist',
  'spotify_track_number',
  'spotify_disc_number',
  'mb_year',
  'mb_year_source',
  'mb_match_method',
  'mb_score',
  'deezer_year',
  'deezer_invalid_year',
  'deezer_status',
  'deezer_track_id',
  'discogs_year',
  'discogs_rejected_year',
  'discogs_rejected_reason',
  'chosen_candidate',
  'status',
  'notes',
  'diff',
  'spotify_track_id',
  'spotify_match_name',
  'spotify_match_artist',
  'match_method',
  'similarity_score',
  'isrc',
  'spotify_found',
  'manual_source_url',
  'exclusion_reason',
  'final_year',
];

const STRONG_EXISTING_SOURCES = new Set(['final_year', 'release_year', 'csv_year']);
const OPEN_STATUSES = new Set([
  'review_needed',
  'review_needed_after_discogs',
  'soft_discogs_pending',
  'spotify_not_found',
  'mb_no_match',
  'mb_match_uncertain',
  'review_needed_other_source_earlier',
  'review_needed_catalog_year_suspected',
  'review_needed_discogs_earlier_than_mb',
  'review_needed_spotify_earlier',
  'review_needed_spotify_deezer_agree_against_mb',
  'manual_skipped',
  'manual_quit_pending',
  'existing_year_conflict',
]);
const MANUAL_FINAL_STATUSES = new Set([
  'manual_kept_existing',
  'manual_confirmed_mb',
  'manual_confirmed_deezer',
  'manual_confirmed_discogs',
  'manual_confirmed_spotify',
  'manual_entered_year',
  'manual_musicbrainz_url',
]);
const MANUAL_STATUSES = new Set([
  ...MANUAL_FINAL_STATUSES,
  'manual_skipped',
  'manual_quit_pending',
  'excluded_from_pool',
]);
const SORT_RANK = {
  soft_discogs_pending: 4,
  review_needed: 4,
  review_needed_after_discogs: 4,
  spotify_not_found: 7,
  manual_quit_pending: 7,
  manual_skipped: 6,
  mb_no_match: 5,
  mb_match_uncertain: 4,
  review_needed_other_source_earlier: 3,
  review_needed_catalog_year_suspected: 4,
  review_needed_discogs_earlier_than_mb: 4,
  review_needed_spotify_earlier: 3,
  review_needed_spotify_deezer_agree_against_mb: 3,
  existing_year_conflict: 2,
  minor_difference: 1,
  mb_uncertain_but_year_consensus: 0,
  auto_accepted_mb: 0,
  auto_accepted_mb_soft_checked: 0,
  mb_anchor_ok: 0,
  existing_year_confirmed: 0,
  manual_kept_existing: 0,
  manual_confirmed_mb: 0,
  manual_confirmed_deezer: 0,
  manual_confirmed_discogs: 0,
  manual_confirmed_spotify: 0,
  manual_entered_year: 0,
  manual_musicbrainz_url: 0,
  excluded_from_pool: 0,
};

module.exports = {
  COLUMNS,
  MANUAL_FINAL_STATUSES,
  MANUAL_STATUSES,
  OPEN_STATUSES,
  SORT_RANK,
  STRONG_EXISTING_SOURCES,
};
